from .cnn_2560_768 import CNN_2560_768
from .cnn_gcforest import TDCNN_GCFOREST
from .wdcnn import WDCNN
from .ticnn import TICNN
from .ma_1dcnn_ import MA_1DCNN
from .mix_cnn_ import MIX_CNN
from .gcforest_ import GC_Forest
from .Linet import LiNet
from .Lenet_5 import LeNet_5
from .onedcnn_softmax import One_Dcnn_Softmax
